### ISSUE TITLE
Is there any missing dependencies?

### ISSUE THREAD

**Issue by kevinorin** [sendgrid/sendgrid-php-example#1]
Running this php gives error:

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/staging.shipmenthq.com/sendgrid-php-example/sendgrid-php-example.php on line 2

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:') in /Applications/MAMP/htdocs/staging.shipmenthq.com/sendgrid-php-example/sendgrid-php-example.php on line 2

**Comment by akifhussain** [comment]
hello dears, I am new here. can some one tell me how to use composer? I am also facing the same issue "failed to open the file vendor/autoload.php".

**Comment by akifhussain** [comment]
I have already installed composer for a framework.. Now where I have to use composer, and which command should I write there?
